language: node_js
node_js: 
  - "node"
  - "lts/*"

before_script:
  - npm install -g @angular/cli

script:
  - ng test --watch false
  - ng build --prod

notifications:
  email:
    on_failure: change
    on_success: change